pipeline:
  trigger:
    image: plugins/downstream
    server: http://drone.astronomer.io
    fork: true
    secrets: [ downstream_token ]
    repositories:
      - astronomer/astronomer
    when:
      branch: master
